DROP SCHEMA IF EXISTS Hunt;

CREATE SCHEMA IF NOT EXISTS Hunt DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
USE Hunt;

DROP TABLE IF EXISTS `User`;
CREATE TABLE IF NOT EXISTS `User` (
    userId INT UNSIGNED NOT NULL AUTO_INCREMENT,
    username VARCHAR(255) NOT NULL,
    Password VARCHAR(255) NOT NULL,
    PRIMARY KEY (userId)
);

DROP TABLE IF EXISTS DungeonLevel;

CREATE TABLE IF NOT EXISTS DungeonLevel (
    dungeonLevelId INT UNSIGNED NOT NULL UNIQUE,
    PRIMARY KEY (dungeonLevelId)
);

DROP TABLE IF EXISTS DungeonRow;

CREATE TABLE IF NOT EXISTS DungeonRow (
    dungeonRow INT UNSIGNED,
    rowTiles TEXT NOT NULL,
    dungeonLevelId INT UNSIGNED NOT NULL
);

DROP TABLE IF EXISTS Player;

CREATE TABLE IF NOT EXISTS Player (
    PlayerId INT UNSIGNED NOT NULL AUTO_INCREMENT,
    PlayerName VARCHAR(255) NOT NULL,
    UserId INT UNSIGNED NOT NULL,
    CurrentDungeonLevelId INT UNSIGNED NOT NULL,
    PlayerStrength INT UNSIGNED NOT NULL DEFAULT 1,
    PlayerAgility INT UNSIGNED NOT NULL DEFAULT 1,
    PlayerVitality INT UNSIGNED NOT NULL DEFAULT 1,
    PlayerDamage INT UNSIGNED NOT NULL DEFAULT 1,
    PlayerSpeed INT UNSIGNED NOT NULL DEFAULT 1,
    PlayerHealthPoints INT UNSIGNED NOT NULL DEFAULT 15,
    PlayerCurrentHealthPoints INT UNSIGNED NOT NULL DEFAULT 15,
    PlayerWeapon VARCHAR(255) NOT NULL DEFAULT 'Fist',
    PlayerArmor VARCHAR(255) NOT NULL DEFAULT 'Flesh',
    PlayerPosX INT UNSIGNED NOT NULL DEFAULT 0,
    PlayerPosY INT UNSIGNED NOT NULL DEFAULT 0,
    PlayerLevel INT UNSIGNED NOT NULL DEFAULT 1,
    PlayerExpForNextLevel INT UNSIGNED NOT NULL DEFAULT 10,
    PlayerExp INT UNSIGNED NOT NULL DEFAULT 0,
    PlayerHunger INT UNSIGNED NOT NULL DEFAULT 100,
    PlayerInventory VARCHAR(255) NOT NULL DEFAULT '',
    PRIMARY KEY (PlayerId),
    FOREIGN KEY (UserId)
        REFERENCES `User` (UserId)
);

DROP TABLE IF EXISTS Monster;

CREATE TABLE IF NOT EXISTS Monster (
    MonsterId INT UNSIGNED NOT NULL AUTO_INCREMENT,
    MonsterType VARCHAR(255) NOT NULL,
    CurrentDungeonLevelId INT UNSIGNED NOT NULL,
    Strength INT UNSIGNED NOT NULL DEFAULT 1,
    Agility INT UNSIGNED NOT NULL DEFAULT 1,
    Vitality INT UNSIGNED NOT NULL DEFAULT 1,
    Damage INT UNSIGNED NOT NULL DEFAULT 1,
    Speed INT UNSIGNED NOT NULL DEFAULT 1,
    HealthPoints INT UNSIGNED NOT NULL DEFAULT 15,
    CurrentHealthPoints INT UNSIGNED NOT NULL DEFAULT 15,
    Weapon VARCHAR(255) NOT NULL DEFAULT 'Null',
    Armor VARCHAR(255) NOT NULL DEFAULT 'Flesh',
    PosX INT UNSIGNED NOT NULL DEFAULT 0,
    PosY INT UNSIGNED NOT NULL DEFAULT 0,
    ExpOnKill INT UNSIGNED NOT NULL DEFAULT 10,
    TurnCount DOUBLE NOT NULL DEFAULT 0,
    PRIMARY KEY (MonsterId)
);

DROP TABLE IF EXISTS TimeFreeze;

CREATE TABLE IF NOT EXISTS TimeFreeze (
    timeFreezeId INT AUTO_INCREMENT,
    timeFreeze INT,
    PRIMARY KEY (timeFreezeId)
);

DROP TABLE IF EXISTS ItemFloor;

CREATE TABLE IF NOT EXISTS ItemFloor (
    itemFloorId INT AUTO_INCREMENT,
    items VARCHAR(255),
    PRIMARY KEY (itemFloorId)
);

DROP TABLE IF EXISTS Projectile;

CREATE TABLE IF NOT EXISTS Projectile (
    projectileId INT AUTO_INCREMENT,
    color VARCHAR(30),
    x INT,
    y INT,
    movX INT,
    movY INT,
    agility INT,
    damage INT,
    PRIMARY KEY (projectileId)
);









